package com.rentalcar.controllers.utils;

public interface ErrorMessage {

    String ERROR_USERNAME_OR_PASSWORD = "ERROR_USERNAME_OR_PASSWORD";
    String ERROR_PASSWORD = "ERROR_PASSWORD";
    String ERROR_EMAIL = "ERROR_EMAIL";
    String ERROR_LOGIN = "ERROR_LOGIN";
    String ERROR_PASSWORD_MATCHES = "ERROR_PASSWORD_MATCHES";
    String ERROR_USER_EXISTS = "ERROR_USER_EXISTS";
    String ERROR_NO_CARS = "ERROR_NO_CARS";
    String ERROR_INVALID_DATE = "ERROR_INVALID_DATE";
    String ERROR_INVALID_CAR_DATA = "ERROR_INVALID_CAR_DATA";
    String ERROR_CLIENT_NAME = "ERROR_CLIENT_NAME";
    String ERROR_CLIENT_PASSPORT = "ERROR_CLIENT_PASSPORT";
    String ERROR_CARD_NUMBER = "ERROR_CARD_NUMBER";
    String ERROR_CARD_EXPIRES_DATE = "ERROR_CARD_EXPIRES_DATE";
    String ERROR_CVV2 = "ERROR_CVV2";
    String ERROR_PRICE = "String ERROR_PRICE";

}